version: "3"

services:
  db:
    image: postgres:12.4
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    ports:
    - "5432:5432"
  server:
    build : .
    volumes:
      - .:/shortener-app
    ports:
      - "8081:8081"
    depends_on:
      - db
